one job

diff --git a/.github/workflows/testsuite.yml b/.github/workflows/testsuite.yml
--- a/.github/workflows/testsuite.yml
+++ b/.github/workflows/testsuite.yml
@@ -61,7 +61,7 @@ jobs:
 
   tests:
     name: "${{ matrix.python-version }} on ${{ matrix.os }}"
-    runs-on: "${{ matrix.os }}-${{ matrix.os-version }}"
+    runs-on: "${{ matrix.arch == 'ppc64le' && fromJSON('["self-hosted", "linux", "ppc64le"]') || fromJSON(format('["{0}-{1}"]', matrix.os, matrix.os-version || 'latest'))}} #${{ matrix.os }}-${{ matrix.os-version }}"
     timeout-minutes: 10
 
     # Don't run tests if the branch name includes "-notests".
@@ -82,6 +82,8 @@ jobs:
           - windows
         os-version:
           - latest
+        arch:
+          - ppc64le  
         python-version:
           # When changing this list, be sure to check the [gh] list in
           # tox.ini so that tox will run properly. PYVERSIONS
@@ -121,11 +123,27 @@ jobs:
         with:
           persist-credentials: false
 
-      - name: "Set up Python"
+      - if: ${{ matrix.arch != 'ppc64le' }}
+        name: "Set up Python"
         uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
         with:
           python-version: "${{ matrix.python-version }}"
           allow-prereleases: true
+
+      - if: ${{ matrix.arch == 'ppc64le' }}
+        name: "Install dependencies"
+        run: |
+          sudo apt update
+          sudo apt install software-properties-common -y
+          sudo add-apt-repository ppa:deadsnakes/ppa -y
+          sudo apt update
+          sudo apt install python${{ matrix.python-version }} python${{ matrix.python-version }}-venv python${{ matrix.python-version }}-dev -y
+          python${{ matrix.python-version }} -m venv myvenv
+          source myvenv/bin/activate
+          python${{ matrix.python-version }} -m pip install --upgrade pip
+          python${{ matrix.python-version }} -m pip install cibuildwheel   
+
+
           # At a certain point, installing dependencies failed on pypy 3.9 and
           # 3.10 on Windows.  Commenting out the cache here fixed it.  Someday
           # try using the cache again.
@@ -166,105 +184,105 @@ jobs:
   # https://github.com/marketplace/actions/alls-green#why
   # https://github.com/orgs/community/discussions/33579
   
-  tests-ppc64le: 
-    name: Tests on ppc64le (self-hosted) ${{ matrix.python-version }}
-    runs-on: self-hosted
-    timeout-minutes: 10
+  # tests-ppc64le: 
+  #   name: Tests on ppc64le (self-hosted) ${{ matrix.python-version }}
+  #   runs-on: self-hosted
+  #   timeout-minutes: 10
 
-    # Don't run tests if the branch name includes "-notests".
-    # Only run tests if files that affect tests have changed.
-    needs: changed
-    if:
-      needs.changed.outputs.run_tests == 'true'
-      && !contains(github.ref, '-notests')
+  #   # Don't run tests if the branch name includes "-notests".
+  #   # Only run tests if files that affect tests have changed.
+  #   needs: changed
+  #   if:
+  #     needs.changed.outputs.run_tests == 'true'
+  #     && !contains(github.ref, '-notests')
 
-    env:
-      TOX_GH_MAJOR_MINOR: "${{ matrix.python-version }}"
+  #   env:
+  #     TOX_GH_MAJOR_MINOR: "${{ matrix.python-version }}"
 
-    strategy:
-      matrix:
+  #   strategy:
+  #     matrix:
         
-        python-version:
-          # When changing this list, be sure to check the [gh] list in
-          # tox.ini so that tox will run properly. PYVERSIONS
-          # Available versions:
-          # https://github.com/actions/python-versions/blob/main/versions-manifest.json
-          # https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#available-versions-of-python-and-pypy
-          - "3.10"
-          - "3.11"
-          - "3.12"
-          - "3.13"
-          - "3.14"
-          - "3.15"
-        #
-        # If we need to exclude any combinations, do it like this:
-        #  exclude:
-        #    # Windows pypy 3.9 and 3.10 get stuck with PyPy 7.3.15.
-        #    - os: windows
-        #      python-version: "pypy-3.10"
-        #
-        # If we need to tweak the os version we can do it with an include like
-        # this:
-        #  include:
-        #    - python-version: "3.12"
-        #      os: "macos"
-        #      os-version: "15"
+  #       python-version:
+  #         # When changing this list, be sure to check the [gh] list in
+  #         # tox.ini so that tox will run properly. PYVERSIONS
+  #         # Available versions:
+  #         # https://github.com/actions/python-versions/blob/main/versions-manifest.json
+  #         # https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#available-versions-of-python-and-pypy
+  #         - "3.10"
+  #         - "3.11"
+  #         - "3.12"
+  #         - "3.13"
+  #         - "3.14"
+  #         - "3.15"
+  #       #
+  #       # If we need to exclude any combinations, do it like this:
+  #       #  exclude:
+  #       #    # Windows pypy 3.9 and 3.10 get stuck with PyPy 7.3.15.
+  #       #    - os: windows
+  #       #      python-version: "pypy-3.10"
+  #       #
+  #       # If we need to tweak the os version we can do it with an include like
+  #       # this:
+  #       #  include:
+  #       #    - python-version: "3.12"
+  #       #      os: "macos"
+  #       #      os-version: "15"
 
-      fail-fast: false
+  #     fail-fast: false
 
-    steps:
-      - name: "Check out the repo"
-        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
-        with:
-          persist-credentials: false
+  #   steps:
+  #     - name: "Check out the repo"
+  #       uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
+  #       with:
+  #         persist-credentials: false
 
-      - name: "Install dependencies"
-        run: |
-          sudo apt update
-          sudo apt install software-properties-common -y
-          sudo add-apt-repository ppa:deadsnakes/ppa -y
-          sudo apt update
-          sudo apt install python${{ matrix.python-version }} python${{ matrix.python-version }}-venv python${{ matrix.python-version }}-dev -y
-          python${{ matrix.python-version }} -m venv myvenv
-          source myvenv/bin/activate
-          python${{ matrix.python-version }} -m pip install --upgrade pip
-          python${{ matrix.python-version }} -m pip install cibuildwheel
+  #     - name: "Install dependencies"
+  #       run: |
+  #         sudo apt update
+  #         sudo apt install software-properties-common -y
+  #         sudo add-apt-repository ppa:deadsnakes/ppa -y
+  #         sudo apt update
+  #         sudo apt install python${{ matrix.python-version }} python${{ matrix.python-version }}-venv python${{ matrix.python-version }}-dev -y
+  #         python${{ matrix.python-version }} -m venv myvenv
+  #         source myvenv/bin/activate
+  #         python${{ matrix.python-version }} -m pip install --upgrade pip
+  #         python${{ matrix.python-version }} -m pip install cibuildwheel
          
-      - name: "Show environment"
-        run: |
-          set -xe
-          python -VV
-          python -m site
-          # For extreme debugging:
-          # python -c "import urllib.request as r; exec(r.urlopen('https://bit.ly/pydoctor').read())"
-          env | sort
-          # Ideally, the system Python wouldn't have writable sitepackages so
-          # try to make it not writable.  We can't always always change the
-          # permissions (Ubuntu & Windows yes, Mac no), so be ready for it to fail.
-          chmod u-w $(python -c "import site; print(site.getsitepackages()[0])") || echo "Couldn't lock down site-packages"
-          ls -ld $(python -c "import site; print(site.getsitepackages()[0])")
-          whoami
+  #     - name: "Show environment"
+  #       run: |
+  #         set -xe
+  #         python -VV
+  #         python -m site
+  #         # For extreme debugging:
+  #         # python -c "import urllib.request as r; exec(r.urlopen('https://bit.ly/pydoctor').read())"
+  #         env | sort
+  #         # Ideally, the system Python wouldn't have writable sitepackages so
+  #         # try to make it not writable.  We can't always always change the
+  #         # permissions (Ubuntu & Windows yes, Mac no), so be ready for it to fail.
+  #         chmod u-w $(python -c "import site; print(site.getsitepackages()[0])") || echo "Couldn't lock down site-packages"
+  #         ls -ld $(python -c "import site; print(site.getsitepackages()[0])")
+  #         whoami
 
-      - name: "Install dependencies"
-        run: |
-          set -xe
-          python -m pip install -r requirements/tox.pip
+  #     - name: "Install dependencies"
+  #       run: |
+  #         set -xe
+  #         python -m pip install -r requirements/tox.pip
 
-      - name: "Run tox for ${{ matrix.python-version }}"
-        run: |
-          python -m tox -- -rfsEX
+  #     - name: "Run tox for ${{ matrix.python-version }}"
+  #       run: |
+  #         python -m tox -- -rfsEX
 
-      - name: "Retry tox for ${{ matrix.python-version }}"
-        if: failure()
-        run: |
-          # `exit 1` makes sure that the job remains red with flaky runs
-          python -m tox -- -rfsEX --lf -vvvvv && exit 1
+  #     - name: "Retry tox for ${{ matrix.python-version }}"
+  #       if: failure()
+  #       run: |
+  #         # `exit 1` makes sure that the job remains red with flaky runs
+  #         python -m tox -- -rfsEX --lf -vvvvv && exit 1
 
   success:
     name: Tests successful
     needs:
       - tests
-      - tests-ppc64le
+      # - tests-ppc64le
     runs-on: ubuntu-latest
     steps:
       - name: Decide whether the needed jobs succeeded or failed
